---
name: default
kind: pipeline
type: docker
trigger:
  event:
    - push
  branch:
    - master

steps:
  - name: install
    image: golang:alpine
    commands:
      - apk add --no-cache --no-progress make
      - make install

  - name: build-update-docker-hub-readme
    image: golang:alpine
    working_dir: /drone/src/update-docker-hub-readme
    commands:
      - apk add --no-cache --no-progress make
      - make -j4 build
    depends_on:
      - install

  - name: build-markdown-toc
    image: golang:alpine
    working_dir: /drone/src/markdown-toc
    commands:
      - apk add --no-cache --no-progress make
      - make -j4 build
    depends_on:
      - install

  - name: publish-update-docker-hub-readme
    image: plugins/docker
    settings:
      repo: cenk1cenk2/pipe-update-docker-hub-readme
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      build_args:
        - PIPE_FILE=./update-docker-hub-readme/dist/update-docker-hub-readme
      tag:
        - latest
    depends_on:
      - build-update-docker-hub-readme

  - name: publish-markdown-toc
    image: plugins/docker
    settings:
      repo: cenk1cenk2/pipe-markdown-toc
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: ./markdown-toc/Dockerfile
      tag:
        - latest
    depends_on:
      - build-markdown-toc
